import '@testing-library/jest-dom';
import { vi } from 'vitest';

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

// Mock de electronAPI global
(window as any).electronAPI = {
  selectDirectory: vi.fn(),
  selectFile: vi.fn(),
  readDirectory: vi.fn(),
  cancelScan: vi.fn(),
  parsePdf: vi.fn(),
  readPdfAsBase64: vi.fn(),
  listFiles: vi.fn(),
  openExternal: vi.fn(),
  exportFile: vi.fn(),
  onScanProgress: vi.fn(),
  offScanProgress: vi.fn(),
  startWatch: vi.fn(),
  stopWatch: vi.fn(),
  onFolderUpdated: vi.fn(),
  offFolderUpdated: vi.fn(),
  getHistory: vi.fn().mockResolvedValue([]),
  saveScan: vi.fn().mockResolvedValue([]),
  deleteScan: vi.fn().mockResolvedValue([]),
  clearHistory: vi.fn().mockResolvedValue(undefined),
  getSettings: vi.fn().mockResolvedValue({
    columns: { invoiceNumber: true, company: true, month: true, year: true, detail: true, filePath: true, amount: true },
    scanning: { onlyCotuFolders: false, ignoreSystemFolders: true, maxDepth: 10 },
    display: { rowsPerPage: 10, compactMode: false },
    customInsurers: []
  }),
  saveSettings: vi.fn().mockImplementation((s) => Promise.resolve(s)),
  ocrExtractText: vi.fn(),
  trimHistory: vi.fn(),
  getDbStats: vi.fn(),
  shell: {
    openPath: vi.fn(),
    openFile: vi.fn(),
    revealInFolder: vi.fn(),
  },
  config: {
    get: vi.fn(),
    set: vi.fn(),
  },
  dashboard: {
    getStats: vi.fn().mockResolvedValue({ pendingDocs: 0 }),
  },
  onSidecarStatus: vi.fn(),
  offSidecarStatus: vi.fn(),
  reconnectSidecar: vi.fn(),
  terapias: {
    ping: vi.fn(),
    checkWord: vi.fn(),
    listDocs: vi.fn(),
    prepare: vi.fn(),
    finalize: vi.fn(),
    getHistory: vi.fn(),
    searchPatient: vi.fn(),
  },
  pdfTools: {
    ping: vi.fn(),
    merge: vi.fn(),
    compress: vi.fn(),
    split: vi.fn(),
    rotate: vi.fn(),
    extract: vi.fn(),
    wordToPdf: vi.fn(),
    pdfToWord: vi.fn(),
    excelToPdf: vi.fn(),
    pptToPdf: vi.fn(),
    deletePages: vi.fn(),
    reorderPages: vi.fn(),
    watermark: vi.fn(),
    watermarkImage: vi.fn(),
    crop: vi.fn(),
    addPageNumbers: vi.fn(),
    jpgToPdf: vi.fn(),
    pdfToJpg: vi.fn(),
    htmlToPdf: vi.fn(),
    protect: vi.fn(),
    unlock: vi.fn(),
    repair: vi.fn(),
    ocr: vi.fn(),
    getPageInfo: vi.fn(),
  }
};
